pipeline:
  name: test3
  identifier: test3
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Poojitha01ai
        repoName: poojitha01-ai
        build: <+input>
  stages:
    - stage:
        name: Build-stage
        identifier: Buildstage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      echo "Hello world"
                      pwd
                      touch poojitha.txt
                      ls -lrtha
              - step:
                  type: Background
                  name: Background_1
                  identifier: Background_1
                  spec:
                    shell: Sh
                    command: echo 'Sample file'
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerconnector
                    repo: poojitha01-ai
                    tags:
                      - latest
