pipeline:
  name: test2
  identifier: test2
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Poojitha01ai
        repoName: poojitha01-ai
        build: <+input>
  stages:
    - stage:
        name: Build stage
        identifier: Build_stage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      echo 'Hello world'
                      pwd
                      touch poojitha.txt
                      ls -lrtha
              - step:
                  type: Background
                  name: Background_1
                  identifier: Background_1
                  spec:
                    shell: Sh
                    command: echo"Hello World"
              - step:
                  type: ArtifactoryUpload
                  name: ArtifactoryUpload_1
                  identifier: ArtifactoryUpload_1
                  spec:
                    connectorRef: ArtifactoryConnector
                    target: artifactory/api/docker/docker
                    sourcePath: docker
